### Creates a new patient entity
POST http://localhost:4001/patients
Content-Type: application/json


{
    "name": "Iman Gadzhi one",
    "email": "iman1141869 41.gadzhi@gmail.com",
    "address": "Dubai",
    "dateOfBirth": "2000-06-09",
    "registeredDate": "2026-01-28"

}


