### Creates a new patient entity
POST http://localhost:4001/patients
Content-Type: application/json


{
    "name": "Bernard Knight",
    "email": "sark12@gmail.com",
    "address": "Takoradi-Apollo",
    "dateOfBirth": "1995-09-09",
    "registeredDate": "2024-11-28"

}



###