spring.application.name=patient-service



# Billing Service gRPC configuration
#billing.service.address=billing-service
#billing.service.grpc.port=9001

# Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Allow bean definition overriding (needed for gRPC compatibility)
server.port=4001
logging.level.root=info
